// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.14.0
// source: two_service_protos/two_service.proto

package two_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByIDPostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetByIDPostReq) Reset() {
	*x = GetByIDPostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIDPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDPostReq) ProtoMessage() {}

func (x *GetByIDPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDPostReq.ProtoReflect.Descriptor instead.
func (*GetByIDPostReq) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetByIDPostReq) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetByIDPostRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
}

func (x *GetByIDPostRes) Reset() {
	*x = GetByIDPostRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByIDPostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDPostRes) ProtoMessage() {}

func (x *GetByIDPostRes) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDPostRes.ProtoReflect.Descriptor instead.
func (*GetByIDPostRes) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIDPostRes) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post *Post `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
}

func (x *UpdatePostReq) Reset() {
	*x = UpdatePostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostReq) ProtoMessage() {}

func (x *UpdatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostReq.ProtoReflect.Descriptor instead.
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePostReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdatePostRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *UpdatePostRes) Reset() {
	*x = UpdatePostRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostRes) ProtoMessage() {}

func (x *UpdatePostRes) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostRes.ProtoReflect.Descriptor instead.
func (*UpdatePostRes) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePostRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadAllPostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID uint32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Sort   string `protobuf:"bytes,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	Limit  string `protobuf:"bytes,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset string `protobuf:"bytes,5,opt,name=Offset,proto3" json:"Offset,omitempty"`
}

func (x *ReadAllPostReq) Reset() {
	*x = ReadAllPostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAllPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPostReq) ProtoMessage() {}

func (x *ReadAllPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPostReq.ProtoReflect.Descriptor instead.
func (*ReadAllPostReq) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAllPostReq) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ReadAllPostReq) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReadAllPostReq) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ReadAllPostReq) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *ReadAllPostReq) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

type ReadAllPostRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Post []*Post `protobuf:"bytes,1,rep,name=Post,proto3" json:"Post,omitempty"`
}

func (x *ReadAllPostRes) Reset() {
	*x = ReadAllPostRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadAllPostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPostRes) ProtoMessage() {}

func (x *ReadAllPostRes) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPostRes.ProtoReflect.Descriptor instead.
func (*ReadAllPostRes) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllPostRes) GetPost() []*Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeletePostReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DeletePostReq) Reset() {
	*x = DeletePostReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostReq) ProtoMessage() {}

func (x *DeletePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostReq.ProtoReflect.Descriptor instead.
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePostReq) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type DeletePostRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePostRes) Reset() {
	*x = DeletePostRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePostRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRes) ProtoMessage() {}

func (x *DeletePostRes) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRes.ProtoReflect.Descriptor instead.
func (*DeletePostRes) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{7}
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID uint32 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Body   string `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_two_service_protos_two_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_two_service_protos_two_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_two_service_protos_two_service_proto_rawDescGZIP(), []int{8}
}

func (x *Post) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Post) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_two_service_protos_two_service_proto protoreflect.FileDescriptor

var file_two_service_protos_two_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x74, 0x77, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x77, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x36,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x25, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x7a, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x37, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x32, 0xa6, 0x02, 0x0a, 0x0f, 0x54, 0x77, 0x6f, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x1b, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e,
	0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64,
	0x41, 0x6c, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x6f, 0x6e,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49,
	0x44, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e,
	0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x77, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_two_service_protos_two_service_proto_rawDescOnce sync.Once
	file_two_service_protos_two_service_proto_rawDescData = file_two_service_protos_two_service_proto_rawDesc
)

func file_two_service_protos_two_service_proto_rawDescGZIP() []byte {
	file_two_service_protos_two_service_proto_rawDescOnce.Do(func() {
		file_two_service_protos_two_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_two_service_protos_two_service_proto_rawDescData)
	})
	return file_two_service_protos_two_service_proto_rawDescData
}

var file_two_service_protos_two_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_two_service_protos_two_service_proto_goTypes = []interface{}{
	(*GetByIDPostReq)(nil), // 0: one_service.GetByIDPostReq
	(*GetByIDPostRes)(nil), // 1: one_service.GetByIDPostRes
	(*UpdatePostReq)(nil),  // 2: one_service.UpdatePostReq
	(*UpdatePostRes)(nil),  // 3: one_service.UpdatePostRes
	(*ReadAllPostReq)(nil), // 4: one_service.ReadAllPostReq
	(*ReadAllPostRes)(nil), // 5: one_service.ReadAllPostRes
	(*DeletePostReq)(nil),  // 6: one_service.DeletePostReq
	(*DeletePostRes)(nil),  // 7: one_service.DeletePostRes
	(*Post)(nil),           // 8: one_service.Post
}
var file_two_service_protos_two_service_proto_depIdxs = []int32{
	8, // 0: one_service.GetByIDPostRes.Post:type_name -> one_service.Post
	8, // 1: one_service.UpdatePostReq.Post:type_name -> one_service.Post
	8, // 2: one_service.ReadAllPostRes.Post:type_name -> one_service.Post
	4, // 3: one_service.TwoMicroservice.Search:input_type -> one_service.ReadAllPostReq
	6, // 4: one_service.TwoMicroservice.Delete:input_type -> one_service.DeletePostReq
	0, // 5: one_service.TwoMicroservice.GetByID:input_type -> one_service.GetByIDPostReq
	2, // 6: one_service.TwoMicroservice.Update:input_type -> one_service.UpdatePostReq
	5, // 7: one_service.TwoMicroservice.Search:output_type -> one_service.ReadAllPostRes
	7, // 8: one_service.TwoMicroservice.Delete:output_type -> one_service.DeletePostRes
	1, // 9: one_service.TwoMicroservice.GetByID:output_type -> one_service.GetByIDPostRes
	3, // 10: one_service.TwoMicroservice.Update:output_type -> one_service.UpdatePostRes
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_two_service_protos_two_service_proto_init() }
func file_two_service_protos_two_service_proto_init() {
	if File_two_service_protos_two_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_two_service_protos_two_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIDPostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByIDPostRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePostRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAllPostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadAllPostRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePostRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_two_service_protos_two_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_two_service_protos_two_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_two_service_protos_two_service_proto_goTypes,
		DependencyIndexes: file_two_service_protos_two_service_proto_depIdxs,
		MessageInfos:      file_two_service_protos_two_service_proto_msgTypes,
	}.Build()
	File_two_service_protos_two_service_proto = out.File
	file_two_service_protos_two_service_proto_rawDesc = nil
	file_two_service_protos_two_service_proto_goTypes = nil
	file_two_service_protos_two_service_proto_depIdxs = nil
}
