// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.14.0
// source: one_service_protos/one_service.proto

package one_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OneMicroserviceClient is the client API for OneMicroservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OneMicroserviceClient interface {
	Upload(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*Response, error)
	Search(ctx context.Context, in *SearchPostReq, opts ...grpc.CallOption) (*SearchPostRes, error)
}

type oneMicroserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewOneMicroserviceClient(cc grpc.ClientConnInterface) OneMicroserviceClient {
	return &oneMicroserviceClient{cc}
}

func (c *oneMicroserviceClient) Upload(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/one_service.OneMicroservice/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oneMicroserviceClient) Search(ctx context.Context, in *SearchPostReq, opts ...grpc.CallOption) (*SearchPostRes, error) {
	out := new(SearchPostRes)
	err := c.cc.Invoke(ctx, "/one_service.OneMicroservice/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneMicroserviceServer is the server API for OneMicroservice service.
// All implementations should embed UnimplementedOneMicroserviceServer
// for forward compatibility
type OneMicroserviceServer interface {
	Upload(context.Context, *RequestParam) (*Response, error)
	Search(context.Context, *SearchPostReq) (*SearchPostRes, error)
}

// UnimplementedOneMicroserviceServer should be embedded to have forward compatible implementations.
type UnimplementedOneMicroserviceServer struct {
}

func (UnimplementedOneMicroserviceServer) Upload(context.Context, *RequestParam) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedOneMicroserviceServer) Search(context.Context, *SearchPostReq) (*SearchPostRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

// UnsafeOneMicroserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OneMicroserviceServer will
// result in compilation errors.
type UnsafeOneMicroserviceServer interface {
	mustEmbedUnimplementedOneMicroserviceServer()
}

func RegisterOneMicroserviceServer(s grpc.ServiceRegistrar, srv OneMicroserviceServer) {
	s.RegisterService(&OneMicroservice_ServiceDesc, srv)
}

func _OneMicroservice_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneMicroserviceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one_service.OneMicroservice/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneMicroserviceServer).Upload(ctx, req.(*RequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _OneMicroservice_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneMicroserviceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/one_service.OneMicroservice/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneMicroserviceServer).Search(ctx, req.(*SearchPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OneMicroservice_ServiceDesc is the grpc.ServiceDesc for OneMicroservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OneMicroservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "one_service.OneMicroservice",
	HandlerType: (*OneMicroserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _OneMicroservice_Upload_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _OneMicroservice_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "one_service_protos/one_service.proto",
}
